title: Allan Dalton

email: allan@helloallan.com
github_url: https://github.com/helloallan
linkedin_url: https://linkedin.com/in/helloallan
medium_url: https://medium.com/@helloallan
twitter_url: https://twitter.com/helloallan

exclude: screenshots, LICENSE, README.md
markdown: kramdown
